# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'

development:
  adapter: mysql2
  encoding: utf8
  database: todoist_development
  username: root

  host: 127.0.0.1
  port: 3306

development_local:
  adapter: mysql2
  encoding: utf8
  database: todoist_development_local
  username: root
  password: ilikerandompasswords
  host: 127.0.0.1
  port: 3306

production:
  adapter: mysql2
  encoding: utf8
  database: todoist_production
  username: root
  password: ilikerandompasswords
  host: 127.0.0.1
  port: 3306

test:
  adapter: mysql2
  encoding: utf8
  database: todoist_test
  username: root
  password: ilikerandompasswords
  host: 127.0.0.1
  port: 3306
